FORMAT: 1A
HOST: https://api.vennfridge.appspot.com/

# VennFridge
VennFridge provides information on and relationships between ingredients, recipes, grocery items, and tags.

## Ingredients Collection [/ingredients]
  
### List Ingredients [GET /ingredients{?page_size}{?page}{?tags}{?sort}]
Retrieve a subset of ingredients based on given parameters.
Each of the links fields is optional.

+ Parameters
    + page_size (number, optional) - the number of results to return. Defaults to 16.
    + page (number, optional) - the page of results to return. Uses 0-based indexing. Defaults to 0.
    + tags (array[String], optional) - array of filtering parameters to apply to results. Defaults to none.
    + sort (String, optional) - sorting parameter to apply to results. Options are alphabetical (alpha) and reverse alphabetical (alpha_reverse). Defaults to alphabetical.

+ Response 200 (application/json)

        
        {
            "data": [
                {
                    "id": 18375,
                    "image": "https://storage.googleapis.com/vennfridge/saved_ingredient_images%2F18375.jpg",
                    "name": "active yeast"
                },
                {
                    "id": 19912,
                    "image": "https://storage.googleapis.com/vennfridge/saved_ingredient_images%2F19912.jpg",
                    "name": "agave nectar"
                },
                {
                    "id": 19334,
                    "image": "https://storage.googleapis.com/vennfridge/saved_ingredient_images%2F15117.jpg",
                    "name": "ahi tuna"
                },
                {
                    "id": 12061,
                    "image": "https://storage.googleapis.com/vennfridge/saved_ingredient_images%2F12061.jpg",
                    "name": "almond"
                }
            ],
            "links": {
                "active": 0,
                "last": "http://api.vennfridge.appspot.com/ingredients?page=82&page_size=4&sort=alpha&tags=Dairy-free",
                "next": "http://api.vennfridge.appspot.com/ingredients?page=1&page_size=4&sort=alpha&tags=Dairy-free"
            }
        }

        
### View Ingredient Details [GET /ingredients/{id}]
Retrieve details of a single ingredient.
Aisle is optional.

+ Parameters
    + id (number, required) - the unique id of the ingredient as an integer
  
+ Response 200 (application/json)
 

        {
            "aisle": "Baking",
            "id": 19334,
            "image": "https://storage.googleapis.com/vennfridge/saved_ingredient_images%2F19334.jpg",
            "name": "brown sugar",
            "related_grocery_items": [
                {
                    "id": 177224,
                    "name": "Mama Lycha Brown Sugar"
                },
                {
                    "id": 118104,
                    "name": "Domino Dark Brown Sugar Pure Cane Sugar"
                },
                {
                    "id": 118200,
                    "name": "Domino Dark Brown Sugar Pure Cane Sugar"
                },
                {
                    "id": 117783,
                    "name": "Hain Pure Foods Organic Brown Sugar"
                },
                {
                    "id": 410376,
                    "name": "La Cena Panela 100% Brown Sugar Cane"
                }
            ],
            "related_recipes": [
                {
                    "id": 477341,
                    "name": "Salted Caramel Dark Chocolate Brownies"
                },
                {
                    "id": 825318,
                    "name": "Pumpkin Sheet Cake with Cream Cheese Frosting"
                },
                {
                    "id": 543277,
                    "name": "No Bake Cheesecake Mousse with Raspberry Sauce"
                },
                {
                    "id": 711303,
                    "name": "Thick and Chewy Black and White Chocolate Chip Cookies with Pecans"
                },
                {
                    "id": 206907,
                    "name": "Crème Anglaise with Brown-Sugared Strawberries"
                }
            ],
            "subsitute_ingredients": [
                "1 cup = 1 cup white sugar + 1/4 cup molasses and decrease the liquid by 1/4 cup"
            ],
            "tags": [
                {
                    "image": "/static/images/Low_FODMAP.png",
                    "name": "Low FODMAP"
                },
                {
                    "image": "/static/images/Very_healthy.png",
                    "name": "Very healthy"
                },
                {
                    "image": "/static/images/Vegan.png",
                    "name": "Vegan"
                },
                {
                    "image": "/static/images/Dairy.png",
                    "name": "Dairy-free"
                }
            ]
        }
         
+ Response 404

## Recipes Collection [/recipes]

### List Recipes [GET /recipes{?page_size}{?page}{?tags}{?sort}]
Retrieve a subset of recipes based on given parameters.
Each of the links fields is optional.

+ Parameters
    + page_size (number, optional) - the number of results to return. Defaults to 16.
    + page (number, optional) - the page of results to return. Uses 0-based indexing. Defaults to 0.
    + tags (array[String], optional) - array of filtering parameters to apply to results. Defaults to none.
    + sort (String, optional) - sorting parameter to apply to results. Options are are alphabetical (alpha), reverse alphabetical (alpha_reverse), increasing preparation time (ready_time_asc) and decrasing preparation time (ready_time_desc). Defaults to alphabetical.

+ Response 200 (application/json)
        

        {
            "data": [
                {
                    "blurb": "If you have roughly <b>2 minutes</b> to spend in the kitchen, 1 Minute Sugar-Free Chocolate Mug Cake {Low Carb, Dairy & Gluten Free} might be a spectacular <b>gluten free and dairy free</b> recipe to try. One portion of this dish contains approximately <b>59g of protein</b>, <b>24g of fat</b>, and a total of <b>480 calories</b>. This recipe serves 1 and costs $4.12 per serving. 1968 people were impressed by this recipe. It is brought to you by Sugar Free Mom. A mixture of salt, Top Sirloin, coconut oil, and a handful of other ingredients are all it takes to make this recipe so tasty. Overall, this recipe earns an <b>outstanding spoonacular score of 95%</b>. Users who liked this recipe also liked Sugar-Free Low Carb Chocolate Chia Pudding {Dairy & Gluten Free}, Sugar Free Crustless Coconut Custard Pie {Dairy Free, Gluten Free & Low Carb}, and Sugar-Free Low-Carb Dairy-Free Chocolate Mousse {GIVEAWAY: Sugar-Free Mom’s New Cookbook}.",
                    "id": 557212,
                    "image": "https://spoonacular.com/recipeImages/1-Minute-Sugar-Free-Chocolate-Mug-Cake-{Low-Carb--Dairy---Gluten-Free}-557212.jpg",
                    "name": "1 Minute Sugar-Free Chocolate Mug Cake {Low Carb, Dairy & Gluten Free}",
                    "ready_time": 2
                },
                {
                    "blurb": "5 Ingredient High Protein Pumpkin Pancakes might be just the morn meal you are searching for. One portion of this dish contains roughly <b>18g of protein</b>, <b>10g of fat</b>, and a total of <b>351 calories</b>. This recipe serves 1 and costs $1.75 per serving. If you have pumpkin pie spice, egg, rolled oats, and a few other ingredients on hand, you can make it. It is a good option if you're following a <b>gluten free and vegetarian</b> diet. It is brought to you by spoonacular user coffeebean. From preparation to the plate, this recipe takes around <b>15 minutes</b>. High Protein Pumpkin Pancakes, Healthy Pumpkin Pancakes (low carb, high protein, gluten free), and 3 Ingredient High Protein Cantaloupe Smoothie are very similar to this recipe.",
                    "id": 157089,
                    "image": "https://spoonacular.com/recipeImages/5-Ingredient-High-Protein-Pumpkin-Pancakes-157089.jpg",
                    "name": "5 Ingredient High Protein Pumpkin Pancakes",
                    "ready_time": 15
                },
                {
                    "blurb": "If you want to add more <b>caveman, gluten free, primal, and vegan</b> recipes to your recipe box, ABC (Apple, Beet, Carrot) juice might be a recipe you should try. One serving contains <b>19 calories</b>, <b>0g of protein</b>, and <b>0g of fat</b>. For <b>15 cents per serving</b>, you get a beverage that serves 8. A mixture of apple, beet, carrot, and a handful of other ingredients are all it takes to make this recipe so delicious. 24 people were impressed by this recipe. It is brought to you by Foodess. From preparation to the plate, this recipe takes around <b>5 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 54%</b>. This score is solid. ABC Juice (Apple Beet Carrot Juice), Heart Healthy and Cleansing Juice: Beet Carrot Apple Lime Orange Ginger Juice, and Juice Without a Juicer: Apple Carrot Beet Ginger Juice are very similar to this recipe.",
                    "id": 611673,
                    "image": "https://spoonacular.com/recipeImages/ABC-(Apple--Beet--Carrot)-juice-611673.jpg",
                    "name": "ABC (Apple, Beet, Carrot) juice",
                    "ready_time": 5
                },
                {
                    "blurb": "ABC Juice (Apple Beet Carrot Juice) could be just the <b>caveman, gluten free, primal, and vegan</b> recipe you've been looking for. This recipe makes 1 servings with <b>137 calories</b>, <b>2g of protein</b>, and <b>1g of fat</b> each. For <b>$1.26 per serving</b>, this recipe <b>covers 7%</b> of your daily requirements of vitamins and minerals. 27 people were impressed by this recipe. It works well as a reasonably priced beverage. It is brought to you by Roti 'n' Rice. From preparation to the plate, this recipe takes about <b>10 minutes</b>. If you have apple, beet, lemon juice, and a few other ingredients on hand, you can make it. Taking all factors into account, this recipe <b>earns a spoonacular score of 62%</b>, which is solid. ABC (Apple, Beet, Carrot) juice, Heart Healthy and Cleansing Juice: Beet Carrot Apple Lime Orange Ginger Juice, and Juice Without a Juicer: Apple Carrot Beet Ginger Juice are very similar to this recipe.",
                    "id": 620307,
                    "image": "https://spoonacular.com/recipeImages/ABC-Juice-(Apple-Beet-Carrot-Juice)-620307.jpg",
                    "name": "ABC Juice (Apple Beet Carrot Juice)",
                    "ready_time": 10
                }
            ],
            "links": {
                "active": 0,
                "last": "http://api.vennfridge.appspot.com/recipes?page=93&page_size=4&sort=alpha",
                "next": "http://api.vennfridge.appspot.com/recipes?page=1&page_size=4&sort=alpha"
            }
        }
        
### View Recipe Details [GET /recipes/{id}]
Retrieve details of a single recipe.

+ Parameters
    + id (number, required) - the unique id of the recipe as an integer
  
+ Response 200 (application/json)
        

        {
            "blurb": "Baked Dorito-Crusted Chicken might be just the main course you are searching for. For <b>$2.62 per serving</b>, this recipe <b>covers 23%</b> of your daily requirements of vitamins and minerals. This recipe makes 2 servings with <b>773 calories</b>, <b>37g of protein</b>, and <b>36g of fat</b> each. If you have cheese tortilla chips, skinless boneless chicken breasts, milk, and a few other ingredients on hand, you can make it. To use up the milk you could follow this main course with the Milky Way Brownie Bites as a dessert. This recipe is liked by 1048 foodies and cooks. It is brought to you by Alidas Kitchen. From preparation to the plate, this recipe takes about <b>45 minutes</b>. It is a good option if you're following a <b>gluten free</b> diet. Overall, this recipe earns a <b>great spoonacular score of 87%</b>. If you like this recipe, you might also like recipes such as Chicken & Dorito Casserole, Dorito Chicken Casserole, and Nacho Cheese Dorito Chicken.",
            "id": 547264,
            "image": "https://spoonacular.com/recipeImages/Baked-Dorito-Crusted-Chicken-547264.jpg",
            "ingredient_list": [
                {
                    "id": 19057,
                    "original_string": "1 cup crushed cheese tortilla chips (or any chip will work here)"
                },
                {
                    "id": 1123,
                    "original_string": "1 egg, lightly beaten"
                },
                {
                    "id": 1077,
                    "original_string": "1 tablespoon milk (I used skim)"
                },
                {
                    "id": 1055062,
                    "original_string": "2 boneless, skinless chicken breasts (4 to 5 ounces each)"
                }
            ],
            "instructions": "Preheat oven to 425 degrees.  Line a baking sheet with foil and spray baking sheet with cooking spray.Put crushed chips in a shallow bowl.In a separate shallow bowl, whisk egg and milk until combined. Dip chicken breasts in milk mixture and then dip in chips, coating the chicken.  Place on prepared baking sheet and lightly spray tops with cooking spray. Bake for 15 to 18 minutes, or until chicken is thoroughly cooked.",
            "name": "Baked Dorito-Crusted Chicken",
            "ready_time": 45,
            "related recipes": [
                {
                    "id": 136513,
                    "name": "Chicken & Dorito Casserole"
                },
                {
                    "id": 526795,
                    "name": "Dorito Chicken Casserole"
                },
                {
                    "id": 136987,
                    "name": "Nacho Cheese Dorito Chicken"
                },
                {
                    "id": 353140,
                    "name": "Dorito Chicken Taco Fingers"
                }
            ],
            "servings": 2,
            "source_url": "http://alidaskitchen.com/2013/04/23/baked-dorito-crusted-chicken/",
            "tags": [
                {
                    "img": "/static/images/tags/Dinner.png",
                    "name": "Dinner"
                },
                {
                    "img": "/static/images/tags/Main_course.png",
                    "name": "Main course"
                },
                {
                    "img": "/static/images/tags/Very_popular.png",
                    "name": "Very popular"
                },
                {
                    "img": "/static/images/tags/Lunch.png",
                    "name": "Lunch"
                },
                {
                    "img": "/static/images/tags/Gluten-free.png",
                    "name": "Gluten-free"
                }
            ]
        }
         
+ Response 404

## Grocery Items Collection [/grocery_items]
  
### List Grocery items [GET /grocery_items{?page_size}{?page}{?tags}{?sort}]
Retrieve a subset of grocery items based on given parameters.
Each of the links fields is optional.

+ Parameters
    + page_size (number, optional) - the number of results to return. Defaults to 16.
    + page (number, optional) - the page of results to return. Uses 0-based indexing. Defaults to 0.
    + tags (array[String], optional) - array of filtering parameters to apply to results. Defaults to none.
    + sort (String, optional) - sorting parameter to apply to results. Options are alphabetical (alpha) and reverse alphabetical (alpha_reverse). Defaults to alphabetical.

+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": 205792,
                    "image": "https://spoonacular.com/productImages/205792-636x393.jpg",
                    "name": "Ziyad Pitted Baking Dates, 13 oz, (Pack of 6)"
                },
                {
                    "id": 78663,
                    "image": "https://spoonacular.com/productImages/78663-636x393.jpg",
                    "name": "Zatarains Creole Mustard"
                },
                {
                    "id": 411204,
                    "image": "https://spoonacular.com/productImages/411204-636x393.jpg",
                    "name": "Zarbee's Naturals Children's Cough Syrup + Mucus Nighttime Grape"
                },
                {
                    "id": 411200,
                    "image": "https://spoonacular.com/productImages/411200-636x393.jpg",
                    "name": "Zarbee's Naturals Baby Cough Syrup + Mucus Grape"
                }
            ],
            "links": {
                "active": 0,
                "last": "http://api.vennfridge.appspot.com/grocery_items?page=344&page_size=4&sort=alpha_reverse&tags=Wheat-free,Soy-free",
                "next": "http://api.vennfridge.appspot.com/grocery_items?page=1&page_size=4&sort=alpha_reverse&tags=Wheat-free,Soy-free"
            }
        }
        
### View Grocery Item Details [GET /grocery_items/{id}]
Retrieve details of a single grocery item.

+ Parameters
    + id (number, required) - the unique id of the grocery item as an integer
  
+ Response 200 (application/json)
        

        {
            "id": 210593,
            "image": "https://spoonacular.com/productImages/210593-636x393.jpg",
            "ingredient_id": 2047,
            "name": "Diamond Crystal Salt - Plain Table",
            "related_grocery_items": [
                {
                    "id": 144734,
                    "name": "Wonderful Almonds Roasted No Salt"
                },
                {
                    "id": 210595,
                    "name": "Diamond Crystal Salt - Sterling"
                },
                {
                    "id": 26813,
                    "name": "Bigs Sunflower Seeds Salted & Roasted Original"
                },
                {
                    "id": 189355,
                    "name": "Elizabeth's Naturals Cashews Roasted No Salt"
                }
            ],
            "tags": [
                {
                    "image": "/static/images/tags/No_additives.png",
                    "name": "No additives"
                },
                {
                    "image": "/static/images/tags/Egg-free.png",
                    "name": "Egg-free"
                },
                {
                    "image": "/static/images/tags/Sulfite-free.png",
                    "name": "Sulfite-free"
                },
                {
                    "image": "/static/images/tags/No_artificial_ingredients.png",
                    "name": "No artificial ingredients"
                },
                {
                    "image": "/static/images/tags/Wheat-free.png",
                    "name": "Wheat-free"
                },
                {
                    "image": "/static/images/tags/Vegetarian.png",
                    "name": "Vegetarian"
                },
                {
                    "image": "/static/images/tags/No_artificial_flavors.png",
                    "name": "No artificial flavors"
                },
                {
                    "image": "/static/images/tags/No_artificial_colors.png",
                    "name": "No artificial colors"
                },
                {
                    "image": "/static/images/tags/Peanut-free.png",
                    "name": "Peanut-free"
                },
                {
                    "image": "/static/images/tags/Corn-free.png",
                    "name": "Corn-free"
                },
                {
                    "image": "/static/images/tags/Pescetarian.png",
                    "name": "Pescetarian"
                },
                {
                    "image": "/static/images/tags/Sugar-free.png",
                    "name": "Sugar-free"
                },
                {
                    "image": "/static/images/tags/Soy-free.png",
                    "name": "Soy-free"
                },
                {
                    "image": "/static/images/tags/Dairy-free.png",
                    "name": "Dairy-free"
                },
                {
                    "image": "/static/images/tags/Grain-free.png",
                    "name": "Grain-free"
                },
                {
                    "image": "/static/images/tags/MSG-free.png",
                    "name": "MSG-free"
                },
                {
                    "image": "/static/images/tags/No_preservatives.png",
                    "name": "No preservatives"
                },
                {
                    "image": "/static/images/tags/Nut-free.png",
                    "name": "Nut-free"
                },
                {
                    "image": "/static/images/tags/Gluten-free.png",
                    "name": "Gluten-free"
                },
                {
                    "image": "/static/images/tags/Vegan.png",
                    "name": "Vegan"
                }
            ],
            "upc": "013600020088"
        }
         
+ Response 404

## Tags Collection [/tags]
  
### List Tags [GET /tags{?page_size}{?page}{?min}{?sort}]
Retrieve a subset of tags based on given parameters.
Each of the links fields is optional.

+ Parameters
    + page_size (number, optional) - the number of results to return. Defaults to 16.
    + page (number, optional) - the page of results to return. Uses 0-based indexing. Defaults to 0.
    + min (number, optional) - Minimum number of elements to which the tags must apply. Defaults to 0.
    + sort (String, optional) - sorting parameter to apply to results. Options are alphabetical (alpha) and reverse alphabetical (alpha_reverse). Defaults to alphabetical.

+ Response 200 (application/json)

        {
            "data": [
                {
                    "blurb": "Contains no gluten.",
                    "image": "Gluten.png",
                    "name": "Gluten-free"
                },
                {
                    "blurb": "Product of animals who primarily ate grains.",
                    "image": "Grain.png",
                    "name": "Grain-free"
                },
                {
                    "blurb": "Product of animals who primarily ate grass.",
                    "image": "Grass.png",
                    "name": "Grass-fed"
                },
                {
                    "blurb": "Small portion of food served before a meal.",
                    "image": "Hor_doeuvre.png",
                    "name": "Hor doeuvre"
                }
            ],
            "links": {
                "active": 5,
                "first": "http://api.vennfridge.appspot.com/tags?page=0&page_size=4&sort=alpha",
                "last": "http://api.vennfridge.appspot.com/tags?page=17&page_size=4&sort=alpha",
                "next": "http://api.vennfridge.appspot.com/tags?page=6&page_size=4&sort=alpha",
                "prev": "http://api.vennfridge.appspot.com/tags?page=4&page_size=4&sort=alpha"
            }
        }
        
### View Tag Details [GET /tags/{tag_name}]
Retrieve details of a single tag.

+ Parameters
    + tag_name (String, required) - the unique name of the tag as a string
  
+ Response 200 (application/json)
    

        {
            "blurb": "Food good for low-carb high-fat diets.",
            "image": "Ketogenic.png",
            "name": "Ketogenic",
            "related_grocery_items": [],
            "related_ingredients": [
                {
                    "id": 18079,
                    "image": "https://cdn.pixabay.com/photo/2016/07/02/17/14/streusel-cake-1493373__340.jpg",
                    "name": "breadcrumbs"
                },
                {
                    "id": 1023,
                    "image": "https://cdn.pixabay.com/photo/2010/12/16/12/08/gruyere-du-savoy-3511_640.jpg",
                    "name": "gruyere cheese"
                },
                {
                    "id": 2025,
                    "image": "https://cdn.pixabay.com/photo/2014/07/11/20/37/nutmeg-390318__340.jpg",
                    "name": "ground nutmeg"
                },
                {
                    "id": 1033,
                    "image": "https://cdn.pixabay.com/photo/2015/10/23/11/23/food-1002838__340.jpg",
                    "name": "parmigiano reggiano"
                },
                {
                    "id": 10023572,
                    "image": "https://cdn.pixabay.com/photo/2016/11/21/15/42/beef-1846030_640.jpg",
                    "name": "ground beef"
                },
                {
                    "id": 6168,
                    "image": "https://cdn.pixabay.com/photo/2015/03/11/23/04/salsa-669389__340.jpg",
                    "name": "hot sauce"
                },
                {
                    "id": 11297,
                    "image": "https://cdn.pixabay.com/photo/2016/09/12/18/27/parsley-1665402_640.jpg",
                    "name": "fresh parsley"
                },
                {
                    "id": 1002030,
                    "image": "https://cdn.pixabay.com/photo/2016/12/06/17/32/pepper-1887035__340.jpg",
                    "name": "black pepper"
                },
                {
                    "id": 1026,
                    "image": "https://cdn.pixabay.com/photo/2015/03/19/22/15/mozzarella-681464__340.jpg",
                    "name": "fresh mozzarella"
                },
                {
                    "id": 1031009,
                    "image": "https://cdn.pixabay.com/photo/2013/08/07/01/08/amsterdam-170394__340.jpg",
                    "name": "sharp cheddar cheese"
                }
            ],
            "related_recipes": [
                {
                    "id": 137715,
                    "image": "https://spoonacular.com/recipeImages/mozzarella-stuffed-pesto-turkey-meatballs-2-137715.jpg",
                    "name": "Mozzarella-Stuffed Pesto Turkey Meatballs"
                },
                {
                    "id": 825201,
                    "image": "https://spoonacular.com/recipeImages/nacho-cheese-sauce-825201.jpg",
                    "name": "Nacho Cheese Sauce"
                },
                {
                    "id": 314892,
                    "image": "https://spoonacular.com/recipeImages/Tater-Tot-Casserole-314892.jpg",
                    "name": "Tater Tot Casserole"
                },
                {
                    "id": 613363,
                    "image": "https://spoonacular.com/recipeImages/Family-Fondue-Night-{My-Favorite-Fondue-+-a-Giveaway}-613363.jpg",
                    "name": "Family Fondue Night {My Favorite Fondue + a Giveaway!}"
                }
            ]
        }
         
+ Response 404