runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:FLASK_APP

runtime_config:
  python_version: 3

#[START cloudsql_settings]
beta_settings:
    # If using Cloud SQL, uncomment and set this value to the Cloud SQL
    # connection name, e.g.
    #   "project:region:cloudsql-instance"
    # You must also update the values in config.py.
    #
    cloud_sql_instances: "vennfridge:us-central1:prod"
#[END cloudsql_settings]
